/**
 * FraudLens AI - Alert Center Dashboard Page
 * Real-time SOC incident feed categorized by severity with immediate playbook execution
 */

window.FraudLensAlertsPage = (function () {
  let activeSeverity = "ALL";

  function render(containerId) {
    const container = document.getElementById(containerId);
    if (!container) return;

    const alerts = window.FraudLensData.alerts;

    container.innerHTML = `
      <div class="page-content alerts-page">
        <!-- Page Header -->
        <div class="page-header-row">
          <div>
            <div class="breadcrumb-tag">INCIDENT RESPONSE</div>
            <h1 class="page-title">Real-Time Alert Center</h1>
            <p class="page-description">
              Prioritized security alerts generated by relational graph anomaly detection and behavioral sequence modeling.
            </p>
          </div>
          <div class="header-action-group">
            <button class="btn btn-demo-pill" onclick="FraudLensModal.showDemoModal()">
              <span>✨</span> Run Judge Demo
            </button>
            <button class="btn btn-danger btn-sm" onclick="FraudLensToast.danger('Emergency Freeze', 'All active critical alerts quarantined.');">
              Quarantine All Critical
            </button>
          </div>
        </div>

        <!-- Severity Filter Pills -->
        <div class="table-toolbar">
          <div class="filter-pills-group">
            <button class="filter-pill ${activeSeverity === 'ALL' ? 'active' : ''}" onclick="FraudLensAlertsPage.setSeverity('ALL')">All Alerts (${alerts.length})</button>
            <button class="filter-pill ${activeSeverity === 'CRITICAL' ? 'active' : ''}" onclick="FraudLensAlertsPage.setSeverity('CRITICAL')">Critical (2)</button>
            <button class="filter-pill ${activeSeverity === 'HIGH' ? 'active' : ''}" onclick="FraudLensAlertsPage.setSeverity('HIGH')">High (2)</button>
            <button class="filter-pill ${activeSeverity === 'MEDIUM' ? 'active' : ''}" onclick="FraudLensAlertsPage.setSeverity('MEDIUM')">Medium (1)</button>
            <button class="filter-pill ${activeSeverity === 'LOW' ? 'active' : ''}" onclick="FraudLensAlertsPage.setSeverity('LOW')">Low / Info (1)</button>
          </div>
        </div>

        <!-- Alerts List -->
        <div class="alerts-feed-container">
          ${renderAlertCards()}
        </div>
      </div>
    `;
  }

  function renderAlertCards() {
    const alerts = window.FraudLensData.alerts;
    const filtered = activeSeverity === "ALL" ? alerts : alerts.filter(a => a.severity === activeSeverity);

    if (filtered.length === 0) {
      return `<div class="empty-alerts-box">No alerts matching selected severity tier.</div>`;
    }

    return filtered.map(alt => {
      const isCrit = alt.severity === "CRITICAL";
      const isHigh = alt.severity === "HIGH";
      const badgeClass = isCrit ? "badge-critical" : (isHigh ? "badge-high" : (alt.severity === "MEDIUM" ? "badge-medium" : "badge-safe"));

      return `
        <div class="alert-card alert-card-${alt.severity.toLowerCase()}">
          <div class="alert-card-top">
            <div class="alert-badge-group">
              <span class="${badgeClass}">${alt.severity}</span>
              <span class="alert-time-tag">⏰ ${alt.time}</span>
              <span class="alert-id-tag font-mono">${alt.id}</span>
            </div>
            <div class="alert-status-pill">${alt.status}</div>
          </div>

          <h3 class="alert-title-text">${alt.title}</h3>
          <p class="alert-description-text">${alt.description}</p>

          <!-- Affected Accounts Strip -->
          <div class="alert-accounts-strip">
            <span class="strip-label">Affected Accounts:</span>
            <div class="account-tags-wrap">
              ${alt.affectedAccounts.map(acc => `<span class="affected-acc-tag font-mono">${acc}</span>`).join(" ")}
            </div>
          </div>

          <!-- Recommended Action & Execution -->
          <div class="alert-action-footer">
            <div class="action-recommendation-group">
              <span class="action-icon">🛡️</span>
              <span class="action-text"><strong>Recommended Action:</strong> ${alt.recommendedAction}</span>
            </div>
            <div class="alert-btn-group">
              ${alt.ringId ? `
                <button class="btn btn-secondary btn-sm" onclick="FraudLensModal.showInvestigationModal('${alt.ringId}')">
                  Investigate Ring (${alt.ringId})
                </button>
              ` : ''}
              <button class="btn ${isCrit ? 'btn-danger' : 'btn-primary'} btn-sm" onclick="FraudLensToast.success('Action Executed', 'Applied: ${alt.recommendedAction}'); this.textContent='Executed ✓'; this.disabled=true;">
                Execute Action
              </button>
            </div>
          </div>
        </div>
      `;
    }).join("");
  }

  function setSeverity(sev) {
    activeSeverity = sev;
    render("appContent");
  }

  return {
    render,
    setSeverity
  };
})();
